### PR TITLE
Update 'aws' required_providers version

### LINKED ISSUE #55: AWS provider version is pinned to 3.40.0
In https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/blob/master/versions.tf#L6 the aws provider version is pinned to 3.40.0. 
```
terraform {
  required_version = ">= 0.12.6"

  required_providers {
    kubernetes = ">= 1.11.4"
    aws        = "~> 3.40.0"
  }
}
```

In our code we are using the latest provider which is 3.49.0.

```
aws = {
      source  = "hashicorp/aws"
      version = "> 3.0, < 4.0"
    }
```

The doc here explicitly says not use `~>` https://www.terraform.io/docs/language/providers/requirements.html#best-practices-for-provider-versions.

Could you fix this so that it does not cause errors for others including your module in their root module?

```
│ Error: Failed to query available provider packages                                     
│                                                                                           
│ Could not retrieve the list of available versions for provider hashicorp/aws: locked provider registry.terraform.io/hashicorp/aws 3.49.0 does not match configured version constraint >= 2.23.0, > 3.0.0, ~> 3.40.0, < 4.0.0; must use
│ terraform init -upgrade to allow selection of new versions                     
╵                                                            
                                                     
```

### PR DESCRIPTION
**Pull request by dgadelha**
Closes #55

### CODE REVIEW

**Comment by DrFaust92** [comment]
Hi @dgadelha im currently on vacation and it seems to be impossible to do from mobile. I’ll to get to a PC and for it but at latest I’ll release on Wednesday.

**Comment by diomalta** [comment]
Hi @DrFaust92 can you release today?

**Comment by DrFaust92** [comment]
released v2.10.0!

**Comment by diomalta** [comment]
Thanks

**Pull request merged**
