### PR TITLE
Add Snapshotter

### PR DESCRIPTION
**Pull request by DrFaust92**

### CODE REVIEW

**Comment by kpbll** [comment]
Hey! Thanks, useful module, I am trying to add snapshot-controller and just checked PRs, so, what about CRDs for snapshot and the storageclass? will you add it to this PR? It is not making sense for me how it should work without that resources, what do you think?

**Comment by DrFaust92** [comment]
The K8s provider doesn't support CRDs so im not sure this can be handled here. ill try to take a look soon

**Comment by kpbll** [comment]
kubernetes-alpha supports any manifests and also kubectl provider too, as an option we can use helm chart for it.

**Comment by DrFaust92** [comment]
You are right but i would like to avoid adding the alpha provider and i'm not sure i would like to add the helm provider either. i might split this to a separate module.

**Pull request closed without merging**
